PlayerTurn technically finished
PlayerTurn works as a void method. When it is an int method, trying to return skill causes the following error:

error CS0103: The name `skill' does not exist in the current context